server:
  port: 30016

spring:
  application:
    name: eureka-server


logging:
  file:
    name: ${spring.application.name}
    path: ./target/logs
  level:
    root: INFO

logstash:
  destination: "1.12.236.101:4560"

eureka:
  instance:
    hostname: node3
  client:
    service-url:
      defaultZone: http://node1:30014/eureka/,http://node2:30015/eureka/

management:
  endpoints:
    web:
      exposure:
        include: info