server:
  port: 30028

spring:
  application:
    name: test-mybatis

logging:
  file:
    name: ${spring.application.name}
    path: ./target/logs
  level:
    root: INFO

logstash:
  destination: "1.12.236.101:4560"

app:
  cluster:
    enabled-cached-id-generator: true
    data-center-id: 1
    worker-id: 1