server:
  port: 30005

spring:
  application:
    name: test-redis
  redis:
    timeout: 5000
    connect-timeout: 10000
    database: 0
    cluster:
      nodes:
        - 1.12.236.101:7001
        - 1.12.236.101:7002
        - 1.12.236.101:7003
        - 1.12.236.101:7004
        - 1.12.236.101:7005
        - 1.12.236.101:7006
    password: 21qaz@!QAZ
    lettuce:
#      宕机超时时间，默认100ms
      shutdown-timeout: 100ms
      pool:
#        连接池池中“空闲”连接的最大数量。使用负值表示无限数量的空闲连接，默认为8
        max-idle: 8
#        最小空闲连接数，默认为0
        min-idle: 0
#        连接池可以分配的最大连接数。使用负值表示没有限制，默认为8
        max-active: 8
#        当连接池耗尽时，在抛出异常之前，连接分配应阻塞的最长时间。使用负值无限期等待，默认为-1
        max-wait: -1
#        空闲连接从运行到退出的时间间隔。当为正时，空闲连接回收线程启动，否则不执行空闲连接回收
#        time-between-eviction-runs:
  cache:
    redis:
      cache-duration:
        user: 10s
        post: 20s
logging:
  file:
    name: ${spring.application.name}
    path: ./target/logs
  level:
    root: INFO

logstash:
  destination: "1.12.236.101:4560"

app:
  enabled-cached-id-generator: true
  cluster:
    data-center-id: 1
    worker-id: 1