server:
  port: 30007

spring:
  application:
    name: test-elasticsearch
  elasticsearch:
    uris: 1.12.236.101:9200
    username: elastic
    password: elastic

logging:
  file:
    name: ${spring.application.name}
    path: ./target/logs
  level:
    root: INFO

logstash:
  destination: "1.12.236.101:4560"

app:
  cluster:
    enabled-cached-id-generator: true
    data-center-id: 1
    worker-id: 1