server:
  port: 30023

spring:
  application:
    name: test-disruptor
logging:
  file:
    name: ${spring.application.name}
    path: ./target/logs
  level:
    root: INFO
app:
  cluster:
    enabled-cached-id-generator: true
    data-center-id: 1
    worker-id: 1
  pool:
    enabled-io-pool: true
    enabled-calculate-pool: true
