server:
  port: 30024

spring:
  application:
    name: test-arthas
logging:
  file:
    name: ${spring.application.name}
    path: ./target/logs
  level:
    root: INFO
app:
  cluster:
    enabled-cached-id-generator: true
    data-center-id: 1
    worker-id: 1
arthas:
  agent-id: ${spring.application.name}
  tunnel-server: ws://localhost:7777/ws